[package]
name = "rusty-locks"
version = "0.1.0"
authors = ["Klaas-Jan Boon <klaas-janboon@live.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
